# Generated by Django 4.0.1 on 2022-01-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundoimobiliario',
            name='vacancia_financeira',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
            preserve_default=False,
        ),
    ]
